### PR TITLE
adapted to new 2.8 api.

### PR DESCRIPTION
**Pull request by ChieVFX**
Hey there! One guy in chat told me he was bummed out about your plugin not working with 2.8. I saw it as an easy fix and decided to help out.
2.8 has a smaller toolbar resulting in very small menu:
https://i.imgur.com/r4oyFK4.png
Other than that - should work the same as 2.79.
Cheers!

### CODE REVIEW

**Comment by PLyczkowski** [comment]
Thanks! Could you split the add-on into 2 versions? baking_namepair_creator_2.79.py and baking_namepair_creator_2.8.py?

**Comment by PLyczkowski** [comment]
Thanks!

**Comment by ChieVFX** [comment]
splitted into 2 files: 2.79(got your latest release) and into 2.8 versions.
In 2.8 added extra buttons for batch-show-hide the renamed objects:
https://imgur.com/rzKjPj1

**Comment by ChieVFX** [comment]
You're welcome.

**Pull request merged**
